<?php
$nationalities_list = [

    "AFGHANISTAN",
    "ALBANIA",
    "ALGERIA",
    "UNITED STATES",
    "ANDORRA",
    "ANGOLA",
    "ANTIGUA AND BARBUDA",
    "ARGENTINA",
    "ARMENIA",
    "AUSTRALIA",
    "AUSTRIA",
    "AZERBAIJAN",

    "BAHAMAS",
    "BAHRAIN",
    "BANGLADESH",
    "BARBADOS",
    "BARBUDA",
    "BOTSWANA",
    "BELARUS",
    "BELGIUM",
    "BELIZE",
    "BENIN",
    "BHUTAN",
    "BOLIVIA",
    "BOSNIA AND HERZEGOVINA",
    "BRAZIL",
    "UNITED KINGDOM",
    "BRUNEI",
    "BULGARIA",
    "BURKINA FASO",
    "MYANMAR",
    "BURUNDI",

    "CAMBODIA",
    "CAMEROON",
    "CANADA",
    "CAPE VERDE",
    "CENTRAL AFRICAN REPUBLIC",
    "CHAD",
    "CHILE",
    "CHINA",
    "COLOMBIA",
    "COMOROS",
    "CONGO",
    "COSTA RICA",
    "CROATIA",
    "CUBA",
    "CYPRUS",
    "CZECH REPUBLIC",

    "DENMARK",
    "DJIBOUTI",
    "DOMINICAN REPUBLIC",
    "NETHERLANDS",

    "TIMOR-LESTE",
    "ECUADOR",
    "EGYPT",
    "UNITED ARAB EMIRATES",
    "EQUATORIAL GUINEA",
    "ERITREA",
    "ESTONIA",
    "ETHIOPIA",

    "FIJI",
    "PHILIPPINES",
    "FINLAND",
    "FRANCE",

    "GABON",
    "GAMBIA",
    "GEORGIA",
    "GERMANY",
    "GHANA",
    "GREECE",
    "GRENADA",
    "GUATEMALA",
    "GUINEA-BISSAU",
    "GUINEA",
    "GUYANA",

    "HAITI",
    "HERZEGOVINA",
    "HONDURAS",
    "HUNGARY",

    "KIRIBATI",
    "ICELAND",
    "INDIA",
    "INDONESIA",
    "IRAN",
    "IRAQ",
    "IRELAND",
    "ISRAEL",
    "ITALY",
    "IVORY COAST",

    "JAMAICA",
    "JAPAN",
    "JORDAN",

    "KAZAKHSTAN",
    "KENYA",
    "SAINT KITTS AND NEVIS",
    "KUWAIT",
    "KYRGYZSTAN",

    "LAOS",
    "LATVIA",
    "LEBANON",
    "LIBERIA",
    "LIBYA",
    "LIECHTENSTEIN",
    "LITHUANIA",
    "LUXEMBOURG",

    "NORTH MACEDONIA",
    "MADAGASCAR",
    "MALAWI",
    "MALAYSIA",
    "MALDIVES",
    "MALI",
    "MALTA",
    "MARSHALL ISLANDS",
    "MAURITANIA",
    "MAURITIUS",
    "MEXICO",
    "MICRONESIA",
    "MOLDOVA",
    "MONACO",
    "MONGOLIA",
    "MOROCCO",
    "LESOTHO",
    "BOTSWANA",
    "MOZAMBIQUE",

    "NAMIBIA",
    "NAURU",
    "NEPAL",
    "NEW ZEALAND",
    "VANUATU",
    "NICARAGUA",
    "NIGER",
    "NORTH KOREA",
    "NORTHERN IRELAND",
    "NORWAY",

    "OMAN",

    "PAKISTAN",
    "PALAU",
    "PANAMA",
    "PAPUA NEW GUINEA",
    "PARAGUAY",
    "PERU",
    "POLAND",
    "PORTUGAL",

    "QATAR",

    "ROMANIA",
    "RUSSIA",
    "RWANDA",

    "SAINT LUCIA",
    "EL SALVADOR",
    "SAMOA",
    "SAN MARINO",
    "SAO TOME AND PRINCIPE",
    "SAUDI ARABIA",
    "SCOTLAND",
    "SENEGAL",
    "SERBIA",
    "SEYCHELLES",
    "SIERRA LEONE",
    "SINGAPORE",
    "SLOVAKIA",
    "SLOVENIA",
    "SOLOMON ISLANDS",
    "SOMALIA",
    "SOUTH AFRICA",
    "SOUTH KOREA",
    "SPAIN",
    "SRI LANKA",
    "SUDAN",
    "SURINAME",
    "ESWATINI",
    "SWEDEN",
    "SWITZERLAND",
    "SYRIA",

    "TAIWAN",
    "TAJIKISTAN",
    "TANZANIA",
    "THAILAND",
    "TOGO",
    "TONGA",
    "TRINIDAD AND TOBAGO",
    "TUNISIA",
    "TURKEY",
    "TUVALU",

    "UGANDA",
    "UKRAINE",
    "URUGUAY",
    "UZBEKISTAN",

    "VENEZUELA",
    "VIETNAM",

    "WALES",

    "YEMEN",

    "ZAMBIA",
    "ZIMBABWE"

];
